apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio
type: Opaque
stringData:
  OPENAI_API_KEY: "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"
